# Generated by Django 5.2.12 on 2026-03-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('seller', 'Продавец'), ('sorter', 'Сортировщик')], default='seller', max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('theme', models.CharField(default='light', max_length=10, verbose_name='Тема')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
